# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lbfgsb3cpp <- function(par, fn, gr, lower, upper, ctrl, rho) {
    .Call(`_lbfgsb3c_lbfgsb3cpp`, par, fn, gr, lower, upper, ctrl, rho)
}

.lbfgsb3cThreadTest <- function(nprob, nthreads) {
    .Call(`_lbfgsb3c_lbfgsb3cThreadTest_`, nprob, nthreads)
}

.lbfgsb3cLmmTest <- function(lmm) {
    .Call(`_lbfgsb3c_lbfgsb3cLmmTest_`, lmm)
}

